version: "3"
services:
  markkubot:
    build: .
    env_file: .env
    depends_on:
    - db
  db:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
    - data-volume:/data/db
volumes:
  data-volume:
